import { faker } from "@faker-js/faker";
import axios, { AxiosError } from "axios";
import { Privacy } from "@/api/baseApiResponseModel/baseApiResponseModel";

const tokens = [
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMDQsImlkIjoiYTBkODM4ZDItNzMxNS00OTE4LTk4NWYtOGQwMjBkYzFmOTJiIn0.ra8QCA_bJoP0MamzbIWih8H9S1BlEfMje_7xLZVhR7c",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMDcsImlkIjoiZjUyNzcxYWItZDAzOS00ZDBjLWI3M2QtYmYxMmFkNmY3YTRmIn0.rNeLemGpyy6kITKwU6VDPts1G8habcJHtJtiKFxni-g",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMTEsImlkIjoiZjBmOGEyOGEtNjM1MS00NzEzLWI4NWMtMTAzOTdlZDRlMTNlIn0.2SU7QNPlwJtC8fRTshMpqo5LKuaCv9XCpFFYjT1lFYY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMTQsImlkIjoiOTU5NzgxMDUtMGQxYi00OTU1LWExODUtYzlkMTVjZDk2YjAzIn0.GjrgM9gSHjb5RMYOhKsP_akWkxqsiRJH1RoTsk-Rw8o",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMTcsImlkIjoiMWRhYmJkYmEtZDE4ZC00ZTgxLWE1N2EtNWY4ZDhkMWJmNThhIn0.BijH0VTqCbcMOdI1iszPnDPe6TY20Bza3cLc9-Ehz-0",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMjEsImlkIjoiOTJmNGYwM2QtMjhjNi00NTk0LWE3NTctOTUyYTNlNGMyMmU3In0.80pRNyAI84aMN-5Q8f84NRFc9SgA_W4wMIl8hWv_T8E",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMjQsImlkIjoiZjVmNWM1YjEtNGE0YS00OGYxLWE0OGQtYjQ3ZjZhYjBkZmFiIn0.DrUFihGrwr0P9iYuh6RawUQ0kDDZx3btyJlie0j-MJI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMjcsImlkIjoiMGVkYTY1MTQtZGVmYi00MjA2LThkOTAtMjMzZDJmMWM3YTRjIn0.fGfdkDFZEZrYck7zogKOJ9joN2ikW_C2D5HjK1g6U1Q",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMzEsImlkIjoiODI3OWFjYmUtMjkxMy00ZGYzLTlmMjAtOTA3MmZlYmE2MzIyIn0.8YAc9JQfzcFur5DERbhZs0CnCG9xGjd9x5REE2mf2II",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMzQsImlkIjoiNjZmY2IzMzgtZjY3MS00MDYyLTlhNDItM2YyMzY3N2MwNzA4In0.JSafmN4ouTaVOdA3SIUV3wmgwARY_VOyZG4bMCzyHe4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwMzcsImlkIjoiNjcxMTVlNTMtYzIxNS00NWU3LTgzYjktNWFjZjJjNjVhNzYzIn0.BzSCYABnQQP2xFtaDfKNzCrA7W2ebC9ApQqb5K4DE1k",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNDEsImlkIjoiMTBjNDAxZjMtNGExZi00YjMxLTkzZDQtNzI1ZTJkNDMxMGNlIn0.8O4Ztvu1STkgKcCn93hvS4SvCU9Lwwey7l5MXQLvulk",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNDQsImlkIjoiNTljOTliNDctNjI3ZC00NzAxLTgyZGMtNmNlMzQ1MzQyOTI2In0.vOpu4EjM7cKNVfqfDOyz4kk-4iSXHV5U97PnXrZPJ7o",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNDgsImlkIjoiOGU4MTMxYWItYjg3Mi00ZTZkLWJlZjItZmNjYmI1NDE4MzU2In0.3ZA2ZG2EZbRzxaG7GKe4Nb2NVEjKuuIPMsIGQ3ArN6w",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNTEsImlkIjoiODRlMDBkOWYtNmJiZS00ZDU0LTg2YjktNmYyYzkzNDRiZmRiIn0.EDtdpi8amp1TpGx6ZIGsZYIfRvaHKEJAA5LlXMmifq8",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNTQsImlkIjoiZTRkNDIzMzEtMGZiYi00NjdiLTg2MTMtZjdiOTliMDBhM2UyIn0.ugPKVPmpvnjFHvF-fDD0bQ3M1qa2yGFOSHbeN5dzmjY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNTgsImlkIjoiZmUyYTY1ZjktZjkzNC00NjJiLWI5NTUtY2FjMjRiNTgzYWRmIn0.jGp15TQpAUOQxb93rIsOcHMooCzN8pfnksrZznvDxoA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNjEsImlkIjoiZDQwNDcwYmItOWNmMS00ODU1LWFkY2UtNDJiYjNkOTAyNjk5In0.otMRIpmj_HKegvHPHUHeamPRXE3tezBgssJpT4_UEA0",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNjgsImlkIjoiYjU2YzVhMzUtOGJmZS00NzFhLWE4OWItZjQ4MDEyYmVlZTgyIn0.A9zajVvBxTx3HLVsUDLm0C1J7AYEMMblRIN2FjwwPu4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNzEsImlkIjoiOGEyMTNhNzEtZjcxNS00NWU2LWJkYjktMWM3MzhlZmY5ZmU2In0.1CDNAG9JAzf-7YRe3DTBqW1dkehV26bgpEz0LXXME28",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNzQsImlkIjoiMWM1MjI0OGItMGNmZi00YjQ0LWJjMzAtMmEyNDQ5YjZkYzA4In0.AiWm1R6Nhcrg6J30mIX1uPZtYf_jmooMzCu8lLpzyOY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwNzgsImlkIjoiNGM3MThhM2EtNGUxNC00OGJlLWE0NDgtNzM3ZjhjMDM1OTdhIn0.y6dkmqmUDRdz38BKGlYNKEPtr-qJRf6LEuRY7QbWCrQ",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwODEsImlkIjoiYzY5ZDJhZWQtMWQwMC00OGE3LWIyZWQtMzNkMmRiN2MzMzJhIn0.EkahnbZesVbNOV--EyYh9owEMXnm7TZOlGgZAonJct4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwODQsImlkIjoiMmQ2ZGI0OGUtMGNkYi00YWQ5LTg0NTAtYTAzOWUzMjVjMGU2In0.5D0O13N9KIizpbp8PWFT4FBUz1sN0Hipdib2X-TjYq0",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwODgsImlkIjoiNzZiZDdhZmQtZWJlNy00MjkwLWFiYzEtOTNkNzMwOTFjOGY1In0.-_GqKQePW_efZy030EfDNBdiyU5MXJxAfw8NUCz1fkU",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwOTEsImlkIjoiZWVhMmQxNTItNjA1ZC00MTVjLWE2NzItN2ZhMThjMTM1NmIyIn0.zmERbzfrH3snYpH8ahGFOB2EoNQ8U28okWyiI8SCGxw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwOTQsImlkIjoiY2YxZWMwMjctYjlhMy00MmExLTk1YzUtYTlhYmIxOGM2N2E0In0.lwuwRDn1M8tWJ0tuPtjcgvE9qVbluWaQQXV7ydzsyVA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYwOTgsImlkIjoiYzA2ZDUxMzAtMjBhZi00YzBkLWExZTItNjRkM2UwMTI2NjA3In0.yCXb58JBxFcKkP1RPUuuZSKmxkhgX2Aa18mwCAEr9NE",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMDEsImlkIjoiMDVjMTYxMzYtZmVlNy00OGNhLTlhOTAtZGJkNDE0N2U4NmE1In0.wIWXmlDhJgAnm-ov5hUSCwUVgdMzwOBblghCeOyF25c",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMDQsImlkIjoiMjZjZGUwNzEtYTEwMS00NzliLTg1M2MtNTkzYzg0OTUxM2U4In0.m4OJvDRsqYmLFJ_NpKvs66CW73XklKsK_wVWyr-2quE",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMDcsImlkIjoiNjRlYTVkNzctMzI0YS00NWVkLWIwMWItYmVjYzc3MThkMGIzIn0.Q78o4uyGNgk68jCpUI7jA6fnppYEMXHf4iR7KRUAUOo",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMTEsImlkIjoiY2M5MTA3ZjAtNWFiOC00OWU2LWI5NWYtMjZjOWMwNzg0MzI3In0.hXsvHDKdoSS5k3V90VsRh2EHYMnr7TTRbzARqTD0IYA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMTQsImlkIjoiNjc4NGZiMjktZmFjOC00MWZkLTk5MDYtNzdkZTI2NzYzYWVhIn0.hisLa32eVPxBKTs2AgRZ83egHjzuRG1jmIoIum-53uw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMTgsImlkIjoiYTUxNGIwNGItZWJiMC00YjJiLThkMzItM2UzZmMyYmEyYzk3In0._RPxVBX2PWbC5C2PgM3xM-NYa5Tvko5SO83z-a-6KAI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMjEsImlkIjoiNzY4ZDBlZTAtYTA5MS00M2U1LWI1ODktMWFmYzJkZWU4MzFiIn0.a6FunkxHaOK5IzQK28bWtOCAc6HHFpWdTQMMHJ2qNWY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMjQsImlkIjoiZTJiNzA0ZGQtYzg5OC00ZjlhLTljNTUtNTBkNDM0ZjRlZmY4In0.0tglFpTghPRuodv5ryArsc9uAkpYCRNyf8a0prZZSA8",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMjgsImlkIjoiZmE3ZTU1ODAtMWZmZS00ODg0LWIwNjAtNzZiZjA5ZmMyMTM2In0.3bpscBQU8CT4lkhjT__7rjB7jDI6qeNYYTckzOeFmgM",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMzEsImlkIjoiNzE4ODgxYWQtZjQ3MS00ZmMwLTkwMTgtMTk1MmJmNWI5NjM1In0.NQC9wDAdFKxzSGvModkph8pRlwJs2bxII7WyI68_x-k",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMzUsImlkIjoiMmY0N2YwMTYtODcxNi00MDhiLWE5NGItMjVjYzBhNGY1M2UxIn0.zH6b8qGT6emUZFLk8S3u3bBFO2A8lPFQC1vTuxyiQ2I",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxMzgsImlkIjoiMWYzMGQ1NDMtMjYzOS00NDE4LThhYTctNWRiNzNlMTY5MGQ3In0.wtnB9sGq4VPOYVOf5nV9p_VUXRcMZAoLfoJP90ayKto",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNDEsImlkIjoiZDhhMDA4MGUtMmFkNC00ZTBlLThhOTktYmJiYmVlMmU1YmJlIn0.Tj6lDO4oVfiqdPlxiO_tR1_-8sl09q2W5pVrsd-6iMY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNDUsImlkIjoiNTk4M2YzM2YtYTA3Mi00MDFmLTlhNWEtZjI0YTY0YjU5ZTYyIn0.PmU3fkNo23-ky-WKPSZ5jycZZVeqvGqGIGTnZBqZF-g",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNDgsImlkIjoiMjEyY2MxYTYtMTVhYS00ZjVlLTliMTQtZTg3MzNhZjcwNTFhIn0.HFNKvQyU_p872ynhDUolXk-r1cgf47Ikp8cYQ06NwZU",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNTEsImlkIjoiMzk2YTZlMTUtYmNhNy00MWFmLWE0NTgtNjA0N2Q4NTY0OTFjIn0.NvLaO7gQSEADJxNxYK2KUn2yp8OKj0SGIu0u6LfkiGw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNTUsImlkIjoiZWVlY2IxNWMtNjczMi00MGIwLWI3Y2QtMThkODlhYjg2ZjIyIn0.wq5hkuQFRNG9gC6POgDbNOXEywmXN9zULU2t14089Fg",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNTgsImlkIjoiMDc3NDg0NmEtYjcxOS00M2NkLTgzMzUtMThkNjA3OWZmYmY1In0.nKvMTJ0lT97IKv1B0U5z2IMkssML-6h_5En_1IZNsB0",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNjIsImlkIjoiM2I2MjBlYjItZDA0YS00YzMzLWJkZTEtYmU5MWJiNjEyNzM3In0.cESBXMRqUG_4esEvBv3mUsFsv3XdxoU3XKZDxIyLzi8",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNjUsImlkIjoiMDQzMDZhODUtMDEyNC00OGQ5LWJkM2ItMGQ1ZTQ5MzRmNDEwIn0.u6YkKtOqpEt1jEFJ4fyMl_2iY-AtTU_BJJQn6CKqAIU",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNjgsImlkIjoiNGNhYjFmZTQtNWFiZS00ZjM5LWI5MmYtN2Q2Njk1NGE2OWU0In0.R_EQwyH9TdtiB4LsHP0HkHDhuLTBz4up2FdpGDgpxlE",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNzIsImlkIjoiMmU3NmQzOTMtODgzZS00MzMwLThkMmUtYjI5NzBhNjk1OTQyIn0.htRl1fc3NmtlxNaOPJEcBZ6wFDJp54Ksvgl7S7om7AA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNzUsImlkIjoiZWRhNWZiMDktNDJmNS00MjkxLThiOGYtMjY4ZmE5YTNlMjNhIn0.NgKQWuOUX62YqzcvzbaYvH7j4vzaZzP-qGKI7QUUbBM",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxNzgsImlkIjoiMjA3ZTZhYTYtM2UyMi00YzUxLTlmMTQtOGUxODBmMGE0NDNhIn0.wIrK36F-0psd-u6IE-4-4Kt0HIRuHd4t-Ljw6uFfnkQ",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxODIsImlkIjoiZDBjMmIyNzktMDFlYS00NTVmLThjMDktOTY4NDVlMTQ4ZTAxIn0.Dv1Rs7pnf0d-8Qypt4INpEV9r-D8Y_qOeo-WjQVkCSY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxODUsImlkIjoiMmNiNjMxNDMtNTc0Ny00NzlkLTkyYjQtNzljNDJjYmMyZTRlIn0.i2_cFdycvGwb4erYjJVQgeBi1kBg2trfxwaofV9XP8Y",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxODksImlkIjoiM2EwOTM3MjktNzc2OS00NTMwLWI0OGItNWU3ZWRiYTkzOGVjIn0.lO-rJSv5JHOcY90QHYeVnmhgQYHeBN2kHv0sWMBme6w",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxOTIsImlkIjoiMWQyYjkxMTYtZTFlOS00N2RlLWJiYjUtZjAxOTM1OWExYjJhIn0.QyWfHMI4x3pYQcvgVKZNwijlq3ZIdZtrLBUuC3YEKRU",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxOTUsImlkIjoiYWYxNDJkZjItOWQ2ZS00OGIwLThlMzQtOTc4MzM4NGNjNTU1In0.MQU4piWvHyTcEMdPY7KX7iy7BmLCG761takUsdvcKSw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYxOTksImlkIjoiZDZhYTNkMmItYWYzZi00MDBlLTg3YTYtMTQ5YTA5NWIyOGQxIn0.maUs3j0YZ7jlm05jkV3itijU-Wm_AOVMmLBYY2Tq_a0",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMDIsImlkIjoiMWQ3OTNlY2UtNWFjOS00ZGNmLWE4NjUtMTQzYmY1ZjAwYzMzIn0.XvUFvhg8S6yt-2_fIxSFKEvSaf-J8GsFH2l4bLfgeSE",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMDUsImlkIjoiMTI0NDFkOWUtNTJhZi00ZGM4LTlmMWQtZGFkMDVlMWRiYWMzIn0.-MgsIKU9bgiOGQrdWTsKTBOpZvfA9HJVI-4Mw0AwmKI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMDksImlkIjoiYWVkMTI4M2EtZGNlYS00NGJkLTgxOGUtZGExZTBhNjVmYTc4In0.iKpIzSADxjwK0mb09lNlu3h8r21r8v1qLyJ7-PiSqZM",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMTIsImlkIjoiODdhY2JjNmQtNDdjZi00YTVlLThiZmUtZGE1MzY2MWRhZjhlIn0.yskH_8MRwLsPjkLY0f_hV8GT35pYv_ftceLPPcN8Jbs",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMTYsImlkIjoiOWUzMjk5YWQtMzQ1NC00NjY4LTlmNzMtMzBhMzk5MzE3YzU3In0.LZt_vD54IljNqCCoAFNI5q_EI7iwGpb16S_RGLxMjlI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMTksImlkIjoiNjgwMjI2NzQtNjg2OS00MjkwLThmOWYtODBhNTA4YTk5OWMxIn0.1QwdVCztORVH2yEVFEGaTiVP5gIQSKfbvJZ03WZUEq0",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMjIsImlkIjoiMGRiOTdjMDEtYTRjZC00ZmY3LWJlY2YtYzAyMTExODE5M2I5In0.QQvpGVNiQnCrdCI3JTxOmfJZeAo_5DbThPi_kdGM4-c",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMjYsImlkIjoiYmFjZTAxYTgtNDgwYy00YTAxLWE2ZmUtMWZkN2ZiMzJiYzhjIn0.eZvuU2cyBX60mx7avF2_tGCJs5Oy-kDvZormD7Yw-jw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMjksImlkIjoiMzU4NDJmNzItNWE2ZC00NGJkLTg0YzktM2JhMjNiMjhhNGZhIn0.eZX-KLEr96YAHdeT0vAVrFcnf55vdz8bHiEhY8q52YA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMzIsImlkIjoiNzI0OGQ2MWItM2VkMS00MGQyLWI0OWUtZmIzMDNmOWIwMjExIn0.HCzQO-f7cR2gKrxNa2gdsJuSbmKkapcDi0CIMaReNr4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMzYsImlkIjoiNzMwNmZhYTQtZDY1MS00ZjdjLThhMGEtN2U4ZjAyNjIyYWMwIn0.nqcPy_pnNOnGTjlSB5Xw8QfEm1WACAxsllpGf77aXeY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyMzksImlkIjoiMmJjZWRjZjktOGNkNS00ZTliLWFlNDUtNDc2NzRkMGU5YzQ5In0.-E5MyqFAyem53QCN2Cv3S6omE4CuSmPnFg2ry8j6o00",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNDIsImlkIjoiNzllM2EzY2MtMjFmYS00ZmVkLTg4MzMtODNhNGM2MTNiNTdjIn0.LaM1CJg7evndJxShD5hQ36-HOs1Xzrkdkaj500qvnWM",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNDYsImlkIjoiM2I4Y2NhYzEtMGQ5MC00MjY2LThhZDgtMDNkYWZlMjc0YWQwIn0.xYA6t6p94NRsG492iRCb_wCpy-WXTFgngfm-3DYCrsI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNDksImlkIjoiOTZlZGZiYTEtNGNkNC00ODJiLWI1MDMtNjQwZmZiZGY4YmRmIn0.-dt0HDDOmfW4-VCPUfLs5ShJgZ5tg8LNXuIso5u0jXc",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNTIsImlkIjoiYTc5MDgzYWEtMmU1YS00MGYyLTgwNTUtYzE2NDNkZWRjMmNmIn0.htDA3xyecabuM259xq7E7iz_gnKbJ1Y6kzy_DDyeACw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNTYsImlkIjoiYTM2MmFjM2UtMzc3OS00OGYzLTk1NTAtOTNmZjcxNDJjYjY5In0.7-w5Z4a-SxJu0zRVmYLtXEUXAZvbExhvQ5qJlx5dKrY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNTksImlkIjoiYTllOGE2YWMtNmQ2YS00OThjLTlmZGMtNzQ4OTNlZDU3YmNhIn0.WrEZoqFI6BHfEdajxXhhczhtP5hJVSj40ImLUAqBlkA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNjMsImlkIjoiY2U2Yzg2MDItY2M3MS00NzUwLTg0MTMtMDc1NTFjZjMyMzNiIn0.outuW2awwrzlGjGg5U8d7nu5uirZMtcMVhuRNp1OwJI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNjYsImlkIjoiNDVhNjdkYjMtMDA3My00ZGM3LWJmNDEtZWVmNWQxOTMyZWJmIn0.LcO_fySHqNvVZm-NChTCVkKAAd1K0a7ttjc34vYdZMI",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNjksImlkIjoiZTczMGRlNjEtNzA0Ni00OWRkLTkzZWQtODkxZWY1YmEwMGEzIn0.xqD4jIrliu1KnParglElfnEVC_lCekcGz5qKa1IK5u8",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNzMsImlkIjoiNGZmMTU1ZWQtYTRjZi00NmExLTk4YTktZDE3MTE1MDI5MTE3In0.cAgiSnicwXMbyJOhJ3TW3Y-Qld_k-SvxbL5MdSf1LW4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNzYsImlkIjoiZDQxZTViZjEtODZiNi00MmM3LWIyZWQtODE0ZGY0MzI4YmRkIn0.Aw0816WmZhfL7TOBIVfk5F2tZirfW7HQCPCkYJJHT8o",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyNzksImlkIjoiZjhlMWYxOWItNjFhNC00MGRlLWI4NzEtZTg5ODgyMDY4NzdjIn0.bUzzwjVSDgRe5tFh-duOaejiNIbUjh11DAXc91fxb-A",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyODMsImlkIjoiZjk0Y2ZkNTgtOTYwMi00ZjRjLWE3N2UtYjc2OWI4ODRlMzAzIn0.3j1vbCcXBlxppFw3nqRITROry1xJr_QAwW4S5Ghdkyw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyODYsImlkIjoiODg4ZDYwMGMtMDY3Mi00NDQ0LWE3NzItZmM5YjU4M2RmZGMyIn0.YqEwge8jqAycx11OL-VlEkVZU7dO8e7fO8dWthu8Wj8",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyOTAsImlkIjoiYWM3MDc0MTctY2I1YS00OTVkLWExYzEtNWJiYzk3YTZmZGJlIn0.NfiR_cRea93-V4r7t5RwKeAZuahOtAPcvGm-VNoTmIw",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyOTMsImlkIjoiZjFlMzJhNmQtZmY2MC00MjhjLWFkZDktODRlMjg5NWYyMWNjIn0.jXmQ2iBQGvpqIw3I1ssR8lOEBwwXdPe0AOKXEqCDc_4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyOTYsImlkIjoiNTE4OTg4NTktYWE4ZS00NTM4LWJlNjMtMGE4ZWE5M2ZlNzc1In0.oYFT29_JDWKscv1Nct6OeplITEZlHxqXTe-JPbAWeGo",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYyOTksImlkIjoiMWE3NWEwMzQtNmYyZi00ZTViLWFjMTEtZjY4ZmU5YmY4NWIxIn0.lsjn_rczmv5VX5_VB3kqrko7ZCD1a79CT504-1J26rc",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMDMsImlkIjoiMzQ0ODZiMGUtMzJiOS00Y2ZiLTg0ZjItOTZkOGZhNjRlMTRhIn0.L1trMZalzf_Q6RH1TGjZV4cTvdjWyPvOB6wTdHrsgxg",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMDYsImlkIjoiN2MyNmQwYmItMTY4YS00YzcyLThmZTAtZjVlY2U2M2UyNGM3In0.eMjx1bsgAJgsrS-qXObOubNCsHc9QEO57nTrvaj3sQ4",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMTAsImlkIjoiY2I3YWRhOTktNzAyNC00YWUxLWIwNGEtODlkMDM3MzliMTM2In0.kGjBfZds_N47SUvS8axOKN0lLro7-PzeSlQJVkYN8iM",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMTMsImlkIjoiYjRmZWMyYTYtMmQzNS00NDliLWI5OWUtZWE4OTAyMGQzOThmIn0.iOr1BfvFGRjyXbtGUbngeINN5wFhftPitJ8TFrYjdo8",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMTYsImlkIjoiZGVkMzhiYjktNDMyZi00OTcyLTgyOWYtNmFjZTlkMTY1Y2MzIn0.3haV7v7D8jQ_eF6v29jnMoXk2xecafABIa15DNXhcjk",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMjAsImlkIjoiYmY3MTBkYmQtMDcyMy00YTA2LTgyNTgtMmQwYjZiZjdmZjFiIn0.Uh8D9Qf_5RgMEmZ-7x1YkM3ChrxvLgVNG47jr3pjElg",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMjMsImlkIjoiYTAzZDhjZDQtYWY0YS00MzgyLTk3NzItOGQ2MmZkN2VjNTBiIn0.BowBtH-2Vai74_GvTKRoIoPVpxsbbHVQDBShPfoNAgA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMjYsImlkIjoiOTY1YjcxZWYtMmJkOS00OWM1LWFkZWUtNjI0MTBhYzUyOWExIn0.DKuSxnfVYYQMhQb0EaYzH6TclSNDy6417OahotA2APs",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMzAsImlkIjoiYTBiZGFhMzEtZWNmZi00ZWFiLTliMjUtMjg0NDYyMDliYzYwIn0.KwuqBpCeG-zoasAnz7-gOKBFFLY6-EtVGIvI3kHZhyY",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMzMsImlkIjoiYzA2YzM5MzYtMGViMS00MzU5LWI1MDEtOWU3MWUxZTkyNWEzIn0.KqJrY5GKJIeio-BggnD801MI-mHOklSdFI__LI2ZPPA",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNzYzMzYsImlkIjoiMmViYzFjNTgtZDgyMi00MTcwLWJjOWYtZWQ5NGM5YzI4YzQ4In0.460h4hgkKrtC6FjJZsskj9TwnceTr0JjJ5Oh8xJVzp0",
];

export interface CreatePostRequestModel {
  content?: string;
  privacy?: Privacy;
  location?: string;
  media?: File[];
  created_at?: string;
  updated_at?: string;
}

const fetchImageFromUrl = async (url: string, filename = "image.jpg"): Promise<File> => {
  const response = await fetch(url);
  const blob = await response.blob();
  return new File([blob], filename, { type: blob.type });
};

const generateFakeMedia = async (): Promise<File[]> => {
  const mediaCount = faker.number.int({ min: 1, max: 3 });
  const mediaItems: File[] = [];

  for (let j = 0; j < mediaCount; j++) {
    const imageUrl = `https://picsum.photos/seed/${faker.string.uuid()}/600/400`;
    const imageFile = await fetchImageFromUrl(imageUrl, `image_${j + 1}.jpg`);
    mediaItems.push(imageFile);
  }

  return mediaItems;
};

const createSinglePost = async (index: number): Promise<CreatePostRequestModel | null> => {
  const media = await generateFakeMedia();

  const post: CreatePostRequestModel = {
    content: faker.hacker.phrase(),
    privacy: Privacy.PUBLIC,
    location: faker.location.city(),
    media,
    created_at: faker.date.recent().toISOString(),
    updated_at: faker.date.recent().toISOString(),
  };

  const formData = new FormData();
  formData.append("content", post.content || "");
  formData.append("privacy", post.privacy || "");
  formData.append("location", post.location || "");
  formData.append("created_at", post.created_at || "");
  formData.append("updated_at", post.updated_at || "");

  post.media?.forEach((file) => {
    formData.append("media", file);
  });

  const token = tokens[index % tokens.length];

  try {
    const response = await axios.post(
      "http://192.168.20.94:8080/v1/2024/posts/",
      formData,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "multipart/form-data",
        },
      }
    );
    console.log(`✅ Created post #${index + 1}`);
    return post;
  } catch (error) {
    const axiosError = error as AxiosError;
    console.error(`❌ Failed to create post #${index + 1}: ${axiosError.message}`);
    if (axiosError.response) {
      console.log("Server response:", axiosError.response.data);
    }
    return null;
  }
};

const delay = (ms: number) => new Promise((res) => setTimeout(res, ms));

const createPostsInBatches = async (total: number, delayMs: number) => {
  for (let i = 0; i < total; i++) {
    await createSinglePost(i);
    await delay(delayMs);
  }

  console.log(`🎉 Finished creating ${total} posts.`);
};

createPostsInBatches(200, 3000);
